name: Linting

on:
  pull_request:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.12.26

      - name: terraform fmt
        run: terraform fmt -check -recursive -diff

      # - name: 'module: terraform init'
      #   run: terraform init -backend=false

      - name: 'sub-modules: terraform validate'
        run: |
          for module in $(find modules -maxdepth 1 -mindepth 1 -type d); do
            cd $module
            terraform init
            terraform validate
            cd -
          done